---

#Example
#    vars:
#      args:
#        add:
#          mounts: "{{site.mounts}}"
#          mount_opts: {uid: "{{site.user}}" ,gid: "{{site.user}}" }

- name: Add mounts
  when: args.add.mounts is defined
  loop: "{{args.add.mounts}}"
  loop_control: {loop_var: mount_item}
  #debug: var=mount_item
  mount:
    src: "{{mount_item.src}}"
    path: "{{mount_item.path}}"
    state: mounted
    opts: bind,{{ mount_item.mode | default('ro') }},auto,gid={{args.add.mount_opts.gid}},uid={{args.add.mount_opts.uid}}
    fstype: none
    boot: yes
